# Generated by Django 4.1.7 on 2023-03-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
