# Generated by Django 4.1.7 on 2023-03-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_student_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
    ]
