# Generated by Django 4.1.7 on 2023-03-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stat', '0002_admindetail_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalYearCSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=20)),
                ('st_attedence', models.CharField(max_length=100)),
                ('st_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FirstYearCSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=20)),
                ('st_attedence', models.CharField(max_length=100)),
                ('st_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondYearCSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=20)),
                ('st_attedence', models.CharField(max_length=100)),
                ('st_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThirdYearCSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=20)),
                ('st_attedence', models.CharField(max_length=100)),
                ('st_year', models.IntegerField()),
            ],
        ),
    ]
