# Generated by Django 4.1.7 on 2023-03-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stat', '0003_finalyearcse_firstyearcse_secondyearcse_thirdyearcse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=20)),
                ('st_roll', models.CharField(max_length=10)),
                ('st_attedence', models.CharField(max_length=100)),
                ('st_year', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ECE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=20)),
                ('st_roll', models.CharField(max_length=10)),
                ('st_attedence', models.CharField(max_length=100)),
                ('st_year', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='EEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=20)),
                ('st_roll', models.CharField(max_length=10)),
                ('st_attedence', models.CharField(max_length=100)),
                ('st_year', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='MECH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=20)),
                ('st_roll', models.CharField(max_length=10)),
                ('st_attedence', models.CharField(max_length=100)),
                ('st_year', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='FinalYearCSE',
        ),
        migrations.DeleteModel(
            name='FirstYearCSE',
        ),
        migrations.DeleteModel(
            name='SecondYearCSE',
        ),
        migrations.DeleteModel(
            name='ThirdYearCSE',
        ),
    ]
