# Generated by Django 4.1.7 on 2023-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stat', '0004_cse_ece_eee_mech_delete_finalyearcse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=20)),
                ('st_roll', models.CharField(max_length=10)),
                ('st_attedence', models.CharField(max_length=100)),
                ('st_year', models.CharField(max_length=6)),
            ],
        ),
    ]
