# Generated by Django 4.1.7 on 2023-03-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stat', '0006_alter_admindetail_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdCSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('CompilerDesign', models.CharField(max_length=120)),
                ('MachineLearning', models.CharField(max_length=120)),
                ('InternetOfThing', models.CharField(max_length=120)),
                ('IPR', models.CharField(max_length=120)),
                ('SoftwareTesting', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='CSE',
        ),
        migrations.DeleteModel(
            name='ECE',
        ),
        migrations.DeleteModel(
            name='EEE',
        ),
        migrations.DeleteModel(
            name='FDT',
        ),
        migrations.DeleteModel(
            name='MECH',
        ),
    ]
