# Generated by Django 4.1.7 on 2023-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stat', '0008_oe'),
    ]

    operations = [
        migrations.AddField(
            model_name='oe',
            name='branch',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
